version: '3.0'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    environment:
      - TZ=${TZ}
    volumes:
      - $PWD/mosquitto/config:/mosquitto/config
      - $PWD/mosquitto/data:/mosquitto/data
      - $PWD/mosquitto/log:/mosquitto/log
    stdin_open: true
    tty: true
    networks:
      mosquitto:
        ipv4_address: 172.19.0.1

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - $PWD/mosquitto/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8074:8080
    environment:
      - TZ=${TZ}
    devices:
      - /dev/ttyZGB:/dev/ttyUSB0
    networks:
      - mosquitto
