version: "3.0"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    user: '1000'
    volumes:
      - $PWD/grafana:/var/lib/grafana:rw
