version: '3.0'

services:
  cf-tunnel:
    container_name: cf-tunnel
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - homeassistant
      - portainer
      - grafana
